SEED:
  default:
    dataset: SEED
    dataset_path: /home/pwjworks/pytorch/emotion_TL-GNNs/ExtractedFeatures/
    processed_path: /home/pwjworks/pytorch/emotion_TL-GNNs/processed_dataset/
    feature: de_LDS
    epochs: 200
    subjects: 15
    pretrain: false
    times: 10
    classes: 3
    channels: 62
    train_setting:
      encoders_num: 1
      gat1: 256
      heads1: 4
      gat2: 256
      heads2: 4
      batch_size: 256
      drop_rate: 0.5
      lr: 0.01